version: "3.8"
services:

  mongodb:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped 
    environment:
      MONGO_INITDB_DATABASE: db
      MONGO_INITDB_ROOT_USERNAME: miguel
      MONGO_INITDB_ROOT_PASSWORD: miguel
    command: mongod --auth 
    volumes:
      - db:/data/db
  api:
    depends_on:
      - mongodb
    container_name: authentication_api
    restart: unless-stopped
    image: api
    build:
      context: ..
      dockerfile: deploy/Dockerfile.api
    ports:
      - 3000:3000
    tty: true

volumes:
    db:
