#To build: sudo docker build -t registry.deti:5000/billsdivider/nginx-proxy-bdapi:16062022  -f deploy/Dockerfile.nginx .
#To add to registry: sudo docker push registry.deti:5000/billsdivider/nginx-proxy-bdapi:16062022 

FROM nginx
COPY deploy/nginx.conf /etc/nginx/nginx.conf
